apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- otel-collector.yaml

# labels:
# - pairs:
#     app.kubernetes.io/part-of: maas-observability
#     app.kubernetes.io/managed-by: maas-observability

configMapGenerator:
- envs:
  - params.env
  name: maas-parameters
generatorOptions:
  disableNameSuffixHash: true
